/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'blog-posts': BlogPost;
    'use-case-pages': UseCasePage;
    'faq-items': FaqItem;
    'invite-requests': InviteRequest;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'use-case-pages': UseCasePagesSelect<false> | UseCasePagesSelect<true>;
    'faq-items': FaqItemsSelect<false> | FaqItemsSelect<true>;
    'invite-requests': InviteRequestsSelect<false> | InviteRequestsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'zh') | ('en' | 'zh')[];
  globals: {
    'site-settings': SiteSetting;
    'faq-page': FaqPage;
    'privacy-page': PrivacyPage;
    'terms-page': TermsPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'faq-page': FaqPageSelect<false> | FaqPageSelect<true>;
    'privacy-page': PrivacyPageSelect<false> | PrivacyPageSelect<true>;
    'terms-page': TermsPageSelect<false> | TermsPageSelect<true>;
  };
  locale: 'en' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 后台角色用于隔离内容、法务、翻译与管理员权限；默认新账号仅具备 viewer 权限。
   */
  roles: ('admin' | 'content-editor' | 'legal-editor' | 'translator' | 'viewer')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  /**
   * 默认模板沿用当前文章结构；HTML 模式只需要 slug 与 HTML 内容。
   */
  renderMode: 'template' | 'html';
  /**
   * 文章标题，同时可作为默认 H1。
   */
  title?: string | null;
  /**
   * 文章 URL slug；上线后应谨慎变更，避免 SEO 权重丢失。
   */
  slug: string;
  /**
   * 仅 HTML 模式使用；前台会在 navbar 与 footer 之间直接渲染这段 HTML。
   */
  htmlContent?: string | null;
  /**
   * Blog 列表卡片顶部图片。
   */
  htmlCardImage?: (number | null) | Media;
  /**
   * Blog 列表卡片第一行左侧标签。
   */
  htmlCardTag?: string | null;
  /**
   * Blog 列表卡片第二行标题；未填写时回退到 slug。
   */
  htmlCardTitle?: string | null;
  /**
   * Blog 列表卡片第三行描述。
   */
  htmlCardDescription?: string | null;
  /**
   * Blog 列表卡片右下角阅读时间，例如 7 min read。
   */
  htmlCardReadingTime?: string | null;
  /**
   * 列表页摘要与分享描述。
   */
  excerpt?: string | null;
  /**
   * 文章页头部导语；未填写时前台可回退到 excerpt。
   */
  lead?: string | null;
  /**
   * 文章卡片与详情页顶部封面图；支持上传 SVG。
   */
  coverImage?: (number | null) | Media;
  /**
   * 作者展示名。
   */
  author?: string | null;
  /**
   * 阅读时长展示文案，例如 7 min read。
   */
  readingTime?: string | null;
  publishedAt?: string | null;
  status: 'draft' | 'review' | 'published';
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 文章页底部推荐阅读；未填写时前台可自动补一个已发布文章。
   */
  relatedPosts?: (number | BlogPost)[] | null;
  /**
   * 营销页统一使用的正文结构；前台会通过视图模型层做二次映射。
   */
  sections?:
    | (
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            style?: ('panel' | 'plain' | 'article') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            style?: ('default' | 'steps' | 'stats') | null;
            /**
             * 默认卡片样式下可选自动计算布局或固定等宽网格。
             */
            layoutMode?: ('auto' | 'fixed') | null;
            cards?:
              | {
                  eyebrow?: string | null;
                  title: string;
                  body?: string | null;
                  paragraphs?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'card-grid-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            style?: ('panel' | 'plain') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bullet-list-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            markdown: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'markdown-document';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            image: number | Media;
            alt?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-section';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-case-pages".
 */
export interface UseCasePage {
  id: number;
  /**
   * 默认模板沿用当前 use case 结构；HTML 模式只需要 slug 与 HTML 内容。
   */
  renderMode: 'template' | 'html';
  /**
   * Use case 路由 slug；应与固定外部 URL 保持一致。
   */
  slug: string;
  /**
   * 仅 HTML 模式使用；前台会在 navbar 与 footer 之间直接渲染这段 HTML。
   */
  htmlContent?: string | null;
  /**
   * 页签与页脚使用的短标题，例如 For Product Managers。
   */
  navigationLabel?: string | null;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    highlight?: string | null;
    description?: string | null;
    supportingText?: string | null;
    footnote?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  heroLead?: string | null;
  painPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  workflowEyebrow?: string | null;
  workflowTitle?: string | null;
  workflowDescription?: string | null;
  workflowSteps?:
    | {
        title: string;
        panelTitle: string;
        panelDescription?: string | null;
        panelMarkdown: string;
        footerLabel?: string | null;
        footerBadge?: string | null;
        id?: string | null;
      }[]
    | null;
  testimonialsEyebrow?: string | null;
  testimonialsTitle?: string | null;
  testimonialsDescription?: string | null;
  testimonials?:
    | {
        quote: string;
        name: string;
        role: string;
        avatar?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  ctaEyebrow?: string | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  /**
   * 营销页统一使用的正文结构；前台会通过视图模型层做二次映射。
   */
  sections?:
    | (
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            style?: ('panel' | 'plain' | 'article') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            style?: ('default' | 'steps' | 'stats') | null;
            /**
             * 默认卡片样式下可选自动计算布局或固定等宽网格。
             */
            layoutMode?: ('auto' | 'fixed') | null;
            cards?:
              | {
                  eyebrow?: string | null;
                  title: string;
                  body?: string | null;
                  paragraphs?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'card-grid-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            style?: ('panel' | 'plain') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bullet-list-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            markdown: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'markdown-document';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            image: number | Media;
            alt?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-section';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer: string;
  /**
   * FAQ 页面中的分组标题，例如 What is Noumi?、Features。
   */
  category: string;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-requests".
 */
export interface InviteRequest {
  id: number;
  /**
   * 申请 invite 的邮箱；同一邮箱重复提交时会刷新上下文信息。
   */
  email: string;
  /**
   * 后台处理状态，用于后续筛选和跟进。
   */
  status: 'new' | 'contacted' | 'invited' | 'archived';
  /**
   * 用户提交申请时所在页面路径。
   */
  sourcePath?: string | null;
  /**
   * 提交请求来源 IP，仅用于排查异常提交。
   */
  ipAddress?: string | null;
  /**
   * 提交请求的 User-Agent，仅用于排查异常提交。
   */
  userAgent?: string | null;
  /**
   * 最近一次提交时间；重复提交会刷新该时间。
   */
  submittedAt: string;
  /**
   * 管理员内部备注，不会展示给用户。
   */
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'blog-posts';
          value: number | BlogPost;
        } | null)
      | ({
          relationTo: 'use-case-pages';
          value: number | UseCasePage;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'use-case-pages';
        value: number | UseCasePage;
      } | null)
    | ({
        relationTo: 'faq-items';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  renderMode?: T;
  title?: T;
  slug?: T;
  htmlContent?: T;
  htmlCardImage?: T;
  htmlCardTag?: T;
  htmlCardTitle?: T;
  htmlCardDescription?: T;
  htmlCardReadingTime?: T;
  excerpt?: T;
  lead?: T;
  coverImage?: T;
  author?: T;
  readingTime?: T;
  publishedAt?: T;
  status?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedPosts?: T;
  sections?:
    | T
    | {
        'rich-text-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        'card-grid-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              columns?: T;
              style?: T;
              layoutMode?: T;
              cards?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    body?: T;
                    paragraphs?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    bullets?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'bullet-list-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        'cta-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              id?: T;
              blockName?: T;
            };
        'markdown-document'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              headerAlignment?: T;
              markdown?: T;
              id?: T;
              blockName?: T;
            };
        'image-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              headerAlignment?: T;
              image?: T;
              alt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-case-pages_select".
 */
export interface UseCasePagesSelect<T extends boolean = true> {
  renderMode?: T;
  slug?: T;
  htmlContent?: T;
  navigationLabel?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        description?: T;
        supportingText?: T;
        footnote?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  heroLead?: T;
  painPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  workflowEyebrow?: T;
  workflowTitle?: T;
  workflowDescription?: T;
  workflowSteps?:
    | T
    | {
        title?: T;
        panelTitle?: T;
        panelDescription?: T;
        panelMarkdown?: T;
        footerLabel?: T;
        footerBadge?: T;
        id?: T;
      };
  testimonialsEyebrow?: T;
  testimonialsTitle?: T;
  testimonialsDescription?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        avatar?: T;
        id?: T;
      };
  ctaEyebrow?: T;
  ctaTitle?: T;
  ctaDescription?: T;
  ctaLabel?: T;
  ctaHref?: T;
  sections?:
    | T
    | {
        'rich-text-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        'card-grid-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              columns?: T;
              style?: T;
              layoutMode?: T;
              cards?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    body?: T;
                    paragraphs?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    bullets?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'bullet-list-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        'cta-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              id?: T;
              blockName?: T;
            };
        'markdown-document'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              headerAlignment?: T;
              markdown?: T;
              id?: T;
              blockName?: T;
            };
        'image-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              headerAlignment?: T;
              image?: T;
              alt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-items_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invite-requests_select".
 */
export interface InviteRequestsSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  sourcePath?: T;
  ipAddress?: T;
  userAgent?: T;
  submittedAt?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * 站点展示名称，用于默认 SEO 标题拼接。
   */
  siteName: string;
  /**
   * 站点完整访问地址，例如 https://www.noumi.ai 。
   */
  siteUrl: string;
  /**
   * 页面未提供更具体描述时的默认 SEO 描述。
   */
  defaultDescription?: string | null;
  /**
   * 官网统一联系邮箱；本项目默认使用 official@noumi.ai。
   */
  contactEmail?: string | null;
  /**
   * 导航右侧按钮文案。
   */
  navCtaText?: string | null;
  /**
   * 导航右侧按钮链接；未填写时前台不展示该按钮。
   */
  navCtaHref?: string | null;
  /**
   * 页脚品牌说明文案。
   */
  footerDescription?: string | null;
  /**
   * 页脚版权文案。
   */
  footerCopyright?: string | null;
  /**
   * 默认分享图；未配置页面级图片时可回退使用。
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * 顶部导航配置；前台会直接读取这里的内容。
   */
  navLinks?:
    | {
        label: string;
        href?: string | null;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 页脚列配置；前台会直接读取这里的内容。
   */
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: number;
  /**
   * 默认模板模式继续读取 FAQ 条目；HTML 模式只需要 HTML 内容。
   */
  renderMode: 'template' | 'html';
  /**
   * 仅 HTML 模式使用；前台会在 navbar 与 footer 之间直接渲染这段 HTML。
   */
  htmlContent?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page".
 */
export interface PrivacyPage {
  id: number;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  /**
   * 默认模板模式沿用当前法律页结构；HTML 模式只需要 HTML 内容。
   */
  renderMode: 'template' | 'html';
  /**
   * 仅 HTML 模式使用；前台会在 navbar 与 footer 之间直接渲染这段 HTML。
   */
  htmlContent?: string | null;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    highlight?: string | null;
    description?: string | null;
    supportingText?: string | null;
    footnote?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  /**
   * 营销页统一使用的正文结构；前台会通过视图模型层做二次映射。
   */
  sections?:
    | (
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            style?: ('panel' | 'plain' | 'article') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            style?: ('default' | 'steps' | 'stats') | null;
            /**
             * 默认卡片样式下可选自动计算布局或固定等宽网格。
             */
            layoutMode?: ('auto' | 'fixed') | null;
            cards?:
              | {
                  eyebrow?: string | null;
                  title: string;
                  body?: string | null;
                  paragraphs?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'card-grid-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            style?: ('panel' | 'plain') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bullet-list-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            markdown: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'markdown-document';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            image: number | Media;
            alt?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-section';
          }
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-page".
 */
export interface TermsPage {
  id: number;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  /**
   * 默认模板模式沿用当前法律页结构；HTML 模式只需要 HTML 内容。
   */
  renderMode: 'template' | 'html';
  /**
   * 仅 HTML 模式使用；前台会在 navbar 与 footer 之间直接渲染这段 HTML。
   */
  htmlContent?: string | null;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    highlight?: string | null;
    description?: string | null;
    supportingText?: string | null;
    footnote?: string | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  /**
   * 营销页统一使用的正文结构；前台会通过视图模型层做二次映射。
   */
  sections?:
    | (
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            style?: ('panel' | 'plain' | 'article') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            columns?: ('2' | '3' | '4') | null;
            style?: ('default' | 'steps' | 'stats') | null;
            /**
             * 默认卡片样式下可选自动计算布局或固定等宽网格。
             */
            layoutMode?: ('auto' | 'fixed') | null;
            cards?:
              | {
                  eyebrow?: string | null;
                  title: string;
                  body?: string | null;
                  paragraphs?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'card-grid-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            style?: ('panel' | 'plain') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bullet-list-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            primaryCtaLabel?: string | null;
            primaryCtaHref?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-section';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            markdown: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'markdown-document';
          }
        | {
            /**
             * 仅在前台存在固定插槽时填写；一般内容块可留空。
             */
            slotKey?: string | null;
            label?: string | null;
            title?: string | null;
            /**
             * 控制角标、标题与描述的对齐方式；留空时沿用当前版式默认对齐。
             */
            headerAlignment?: ('left' | 'center' | 'right') | null;
            image: number | Media;
            alt?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-section';
          }
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  defaultDescription?: T;
  contactEmail?: T;
  navCtaText?: T;
  navCtaHref?: T;
  footerDescription?: T;
  footerCopyright?: T;
  defaultOgImage?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  renderMode?: T;
  htmlContent?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page_select".
 */
export interface PrivacyPageSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  renderMode?: T;
  htmlContent?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        description?: T;
        supportingText?: T;
        footnote?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  sections?:
    | T
    | {
        'rich-text-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        'card-grid-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              columns?: T;
              style?: T;
              layoutMode?: T;
              cards?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    body?: T;
                    paragraphs?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    bullets?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'bullet-list-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        'cta-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              id?: T;
              blockName?: T;
            };
        'markdown-document'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              headerAlignment?: T;
              markdown?: T;
              id?: T;
              blockName?: T;
            };
        'image-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              headerAlignment?: T;
              image?: T;
              alt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-page_select".
 */
export interface TermsPageSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  renderMode?: T;
  htmlContent?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        description?: T;
        supportingText?: T;
        footnote?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  sections?:
    | T
    | {
        'rich-text-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        'card-grid-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              columns?: T;
              style?: T;
              layoutMode?: T;
              cards?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    body?: T;
                    paragraphs?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    bullets?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'bullet-list-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        'cta-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              description?: T;
              headerAlignment?: T;
              primaryCtaLabel?: T;
              primaryCtaHref?: T;
              secondaryCtaLabel?: T;
              secondaryCtaHref?: T;
              id?: T;
              blockName?: T;
            };
        'markdown-document'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              headerAlignment?: T;
              markdown?: T;
              id?: T;
              blockName?: T;
            };
        'image-section'?:
          | T
          | {
              slotKey?: T;
              label?: T;
              title?: T;
              headerAlignment?: T;
              image?: T;
              alt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'blog-posts';
          value: number | BlogPost;
        } | null)
      | ({
          relationTo: 'use-case-pages';
          value: number | UseCasePage;
        } | null);
    global?: ('site-settings' | 'faq-page' | 'privacy-page' | 'terms-page') | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}